[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPackages = [
  "build-essential",
  "python3-dev"      
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"